### ISSUE TITLE
Problem: epel-release package is not installed using Ansible on RHEL 7.5

### ISSUE THREAD

**Issue by mamedin** [archivematica/Issues#155]
**Expected behaviour**

When installing Archivematica using deploy-pub to a RHEL 7.5 machine, the epel-release repo should be enabled by the ansible-archivematica-src role

**Current behaviour**

When running this ansible role, the `epel-release` package is not available.

**Steps to reproduce**

I tested on a clean RHEL 7.5, and there's no epel-release package available:

<pre>
[root@localhost ~]# cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 7.5 (Maipo)

[root@localhost ~]# sudo yum install epel-release
Loaded plugins: product-id, search-disabled-repos, subscription-manager
No package epel-release available.
Error: Nothing to do
</pre>

**Your environment (version of Archivematica, OS version, etc)**
AM version: stable/1.7.x
OS: RHEL 7.5

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Release documentation (e.g. release notes, wiki documentation, etc) regarding this issue has been written 👍

**Comment by mamedin** [comment]
To add the `epel-release` repo on RHEL 7.5, the https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm package has to be installed first, for example:

```
    - name: "Install EPEL repository on RHEL"
      become: "yes"
      yum:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
        state: present
      when: ansible_distribution == 'RedHat'

    - name: "Add rhel-*-optional-rpms repo on RHEL"
      become: "yes"
      command: subscription-manager repos --enable "rhel-*-optional-rpms" --enable "rhel-*-extras-rpms"
      when: ansible_distribution == 'RedHat'
```

NOTE: about the second repo added, on RHEL 7 it is recommended to also enable the optional and extras repositories since EPEL packages may depend on packages from these repositories

More info at:
https://aws.amazon.com/premiumsupport/knowledge-center/ec2-enable-epel/
https://fedoraproject.org/wiki/EPEL
