### ISSUE TITLE
Problem: Archivematica ansible role fails when using custom facts in remote server and AWX with ansible 2.15 (get_url with become_user module)

### ISSUE THREAD

**Issue by mamedin** [archivematica/Issues#1633]
**Expected behaviour**

The archivematica role should work

**Current behaviour**

When using custom facts in remote server to speed up the deployment (see [
](https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_vars_facts.html#adding-custom-facts) ) and AWX with ansible 2.15, the get_url module requires `allow_world_readable_tmpfiles: true` and fails with the following:

![image](https://github.com/archivematica/Issues/assets/10259133/8127e38f-08af-41b0-936d-960575d0cd3d)

**Steps to reproduce**

Deploy AM1.15 (it only fails the first time AM is deployed from AWX) with AWX, ansible 2.15 and having custom facys in remote server

**Your environment (version of Archivematica, operating system, other relevant details)**

AWX with ansible 2.15
Remote server: AM 1.15, Ubuntu 22.02, using ansible custom facts

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by mamedin** [comment]
The issue is located in the following task:
[
](https://github.com/artefactual-labs/ansible-archivematica-src/blob/9d8c03f276481878855b47adfeb21ddaa844d0ef/tasks/common.yml#L71-L77)

```
  - name: "Download get-pip.py in archivematica userdir"
    become: "yes"
    become_user: "archivematica"
    get_url:
      url: "https://bootstrap.pypa.io/get-pip.py"
      force: "yes"
      dest: "/var/lib/archivematica/get-pip.py"
```

Using the following task we can skip the become_user and `allow_world_readable_tmpfiles: true`:

```
  - name: "Download get-pip.py in archivematica userdir"
    get_url:
      url: "https://bootstrap.pypa.io/get-pip.py"
      force: "yes"
      dest: "/var/lib/archivematica/get-pip.py"
      owner: "archivematica"
      group: "archivematica"
```
