### ISSUE TITLE
Problem: ansible role adds GPG locations as default locations

### ISSUE THREAD

**Issue by mamedin** [archivematica/Issues#891]
**Expected behaviour**

The `ansible-archivematica-role` should configure the GPG locations as non-default locations.

**Current behaviour**

The `ansible-archivematica-role` should configure the GPG locations as default locations.

GPG Backlog is using the GPG AIPsStore description and path.

**Steps to reproduce**

Deploying archivematica qa/1.x with ansible-archivematica-role qa/1.x with variable:

```

archivematica_src_configure_gpg:
  gpg_home_directory: "/var/archivematica/storage_service"
  binary: "gpg"
  key_user: "{{ archivematica_src_configure_ss_user }}"
  key_passphrase: "passphrase"
  key_comment: "Ansible Generated"
  key_mail: "{{ archivematica_src_configure_ss_email }}"
  space_staging_directory: "/var/archivematica/storage_service"
  aipstore_path: "/var/archivematica/sharedDirectory/www/GPG_AIPsStore"
  aipstore_description: "GPG AIPsStore"
  backlog_path: "/var/archivematica/sharedDirectory/www/GPG_transferBacklog"
  backlog_description: "GPG TransferBacklog"
```

**Your environment (version of Archivematica, OS version, etc)**

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Done:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍
