### ISSUE TITLE
Problem: The testing of encrypted packages in AMAUAT generates ambiguous output

### ISSUE THREAD

**Issue by ross-spencer** [archivematica/Issues#893]
**Please describe the problem you'd like to be solved.**

Currently, testing a SIP or AIP is encrypted in AMAUAT tests uses 7z. If we cannot open one of these packaged using this tool, there is an error:

* `Open ERROR: Can not open the file as [7z] archive`

Which effectively tells us, "okay, this was encrypted"

```Python
    aip_local_path = context.am_user.decompress_package(aip_local_path)
    # ``decompress_package`` will attempt to decompress the package with 7z and
    # we expect it to fail because the AIP file is encrypted with GPG.
    aip_is_encrypted = aip_local_path is None
    return aip_is_encrypted
```

**Describe the solution you'd like to see implemented.**

I'd like to make the assertion less ambiguous, and potentially less prone to error, e.g. what if there is another reason the file couldn't be opened for a different reason?

One mechanism might be to use the output of a command such as `file` e.g. `amauat-transfer_1567544004-0bd3cf72-4fe6-4465-aafc-8217ac4127bd.7z: PGP RSA encrypted session key - keyid: B058350D 1E42CEC1 RSA (Encrypt or Sign) 4096b`. 

Another, might be to see if it is feasible, and/or desirable to teach PRONOM to identify encrypted 7z files, which at present, using our own default Siegfried settings, it doesn't seem to know about:
```yaml
---
siegfried   : 1.7.10
scandate    : 2019-09-03T21:03:05Z
signature   : archivematica.sig
created     : 2018-09-19T11:32:33+10:00
identifiers : 
  - name    : 'archivematica'
    details : 'fddXML.zip (DROID_SignatureFile_V94.xml, container-signature-20180917.xml); extensions: archivematica-fmt2.xml, archivematica-fmt3.xml, archivematica-fmt4.xml, archivematica-fmt5.xml'
---
filename : '0bd3/cf72/4fe6/4465/aafc/8217/ac41/27bd/amauat-transfer_1567544004-0bd3cf72-4fe6-4465-aafc-8217ac4127bd.7z'
filesize : 26747
modified : 2019-09-03T20:54:22Z
errors   : 
matches  :
  - ns      : 'archivematica'
    id      : 'UNKNOWN'
    format  : 
    version : 
    mime    : 
    basis   : 
    warning : 'no match; possibilities based on extension are fmt/484'
```

**Describe alternatives you've considered.**

We can leave it as-is of course, and the future of this test still needs to be understood.

**Additional context**

This is one of the issues seen during the AMAUAT testing phase of `1.10`. 

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Done:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍
